#release configuration
#Mon Mar 24 15:10:48 GMT+04:00 2025
completedPhase=check-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.am.capstone\:capstone-data.empty=true
project.scm.am.capstone\:capstone-web.empty=true
project.scm.am.capstone\:project.connection=
project.scm.am.capstone\:project.developerConnection=scm\:git\:git@github.com\:kzakaryan/project.git
project.scm.am.capstone\:project.tag=
project.scm.am.capstone\:project.url=
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:kzakaryan/project.git
